apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: function-with-env
spec:
  runtime: nodejs12
  env:
    - name: CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: clientid
          name: secretforfunction
    - name: CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: clientsecret
          name: secretforfunction
    - name: CONFIG
      valueFrom:
        configMapKeyRef:
          key: configone
          name: configforfunction
    - name: BASE_URL
      valueFrom:
        configMapKeyRef:
          key: baseurl
          name: configforfunction
  deps: |
    {
      "name": "function-with-env",
      "version": "1.0.0",
      "dependencies": {
        "axios": "^0.21.1",
        "qs": "^6.9.4"
      }
    }
  source: |
    const axios = require("axios")
    const qs = require("qs")
    
    module.exports = {
      main: async function (event, context) {
          console.log("------------------")

          console.log("Values from Secret")
          console.log("------------------")
          console.log(process.env['CLIENT_ID'])
          console.log(process.env['CLIENT_SECRET'])

          console.log("------------------")

          console.log("Values from ConfigMap")
          console.log("------------------")
          console.log(process.env['CONFIG'])
          console.log(process.env['BASE_URL'])
      }
    }
